name = "Vulpinian Skies"
author = "Aurora_Luciri"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d95f4098c52c17ad953cbb51cf2f3dfc4b0a024ff3d4aab64d58fffd9352fba"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
