name = "Vulpinian Skies"
author = "Aurora_Luciri"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1092eafccbd287cfa1eb87b98185d229ebc236c76ec8fc2c279fffa56f6fbe7"

[versions]
forge = "47.4.8"
minecraft = "1.20.1"
