name = "Vulpinian Skies"
author = "Aurora_Luciri"
version = "0.0.2b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1c2c501ae9690373d251ae4b4c6f8df54ffbcb6ebfe63f3e87364fa4d56a388"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
