name = "Vulpinian Skies"
author = "Aurora_Luciri"
version = "0.0.1b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9525857764ecf1596fd490a29ffb56a941288e3678b915b2d57dba0dd6153db2"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
