name = "Vulpinian Skies"
author = "Aurora_Luciri"
version = "0.0.3e"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "992f47330210fa1dfb4a81f2d0d788102bad108cd742bec816523e2bdda7ccba"

[versions]
forge = "47.3.29"
minecraft = "1.20.1"
